# Generated by Django 5.2.12 on 2026-04-03 04:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('dean', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colleges/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSUProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('degree_level', models.CharField(choices=[('BS', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BSED', 'Bachelor of Secondary Education'), ('BEED', 'Bachelor of Elementary Education')], max_length=10)),
                ('description', models.TextField()),
                ('duration_years', models.IntegerField(choices=[(4, '4 Years'), (5, '5 Years')])),
                ('tuition_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('required_hs_subjects', models.TextField(blank=True)),
                ('career_paths', models.TextField()),
                ('ideal_skills', models.TextField()),
                ('ideal_interests', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='recommendation.college')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'college')},
            },
        ),
    ]
